### PR TITLE
add support for light hide and seek

### PR DESCRIPTION
**Pull request by queeek180**
support light hide and seek. won't work with other versions of hide and seek

### CODE REVIEW

**Comment by queeek180** [comment]
oops, didnt make a new branch before submitting a pull request. only applicable commit is the first one, the others are just font changes

**Comment by LLytho** [comment]
Sorry for the late response. I must have missed my notifications. 
I currently have no time to test the hide and seek, I assume you have tested it?

**Comment by queeek180** [comment]
Yes, I tested it. it should work only for light hide and seek, and not the original

**Comment by LLytho** [comment]
Update also pushed to workshop. Ty

**Pull request merged**
